### PR TITLE
Tweak README with inline config comments for clarity

### PR DESCRIPTION
**Pull request by longzheng**
Added some inline comments to the config JSON in the README to provide some clarity around the different options.

I know some of this is annotated by `config.schema.json` but for users who's just trying to understand the plugin, hopefully this is helps.

### CODE REVIEW

**Comment by kushagharahi** [comment]
Hi thank you for this contribution! Do you know if someone copy and pastes the config with these comments added, will homebridge ignore the comments?

**Comment by longzheng** [comment]
Unfortunately no, the comments won't be ignored and so it's invalid. Let me try another approach.

**Comment by longzheng** [comment]
@kushagharahi I tried another approach by documenting it underneath the config.

**Review by kushagharahi — APPROVED** [review]
LGTM, thank you for the contribution!

**Pull request merged**
